name: OJC Technologies
markdown: kramdown

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "pure-simple"
