name: OJC Technologies
markdown: kramdown
highlighter: rouge
timezone: Europe/London

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:categories/:year/:month/:day/:title/
