name: OJC Technologies
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: crafty
